# Generated by Django 4.1.7 on 2023-06-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='opening_time',
            field=models.TimeField(),
        ),
    ]
