# Generated by Django 4.1.7 on 2023-06-18 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('coreapp', '0002_medical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medical',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical', to='user.patientprofile'),
        ),
    ]
